### ISSUE TITLE
Geometry optimization and potential optimization don't go together

### ISSUE THREAD

**Issue by pdmmicc** [zoowe/tpot#10]
Hi all,

I'm currently using TPOT for some test runs on Ag111 surface.

I find that VASP calculations stop upon the force convergence criteria for geometry optimizations, without the target potential being reached within TPOTVDIFF. 

Is there any way to simultaneously reach force criteria + target potential? For now, I'm reaching the target potential by setting IBRION=-1 on a geo-opt structure near the target potential (although not fully within TPOTVDIFF), and only altering the NELECT. 

Here's part of my INCAR:

##GEO-opt related
NELMIN = 4 ; NELM = 200
EDIFF = 1E-5 ; EDIFFG = -0.01
NSW = 999 ; IBRION = 2

##TPOT-related
LTPOT               = .TRUE.   # Turn on/off TPOT
TPOTMETHOD          = 2        # Optimize NELECT for scf (1) or ionic (2) step.
TPOTTRUEVACLEVEL    = .TRUE.   # Use true vacuum level or FERMI_SHIFT
TPOTVTARGET         = 2.8400   # Target potential
TPOTVDIFF           = 0.0001   # Potential Threshold
TPOTVRATE           = -1.0     # Initial Rate of changing NELECT, V/electron
TPOTVRATELIM        = 0.1      # Limit for |TPOTVRATE|, V/electron
TPOTVRATEDAMP       = 1.0      # Damping factor for |TPOTVRATE|
TPOTVEDIFF          = 1.d-4    # Energy threshold of electronic iteration to start updating NELECT
TPOTDYNVRATE        = .TRUE.   # Updating NELECT with VRATE
TPOTELECTSTEP       = 0.1      # (Maximum) Amount of electrons changed.
TPOTDFERMI_SHIFTLIM = 0.5      # Limit for change in FERMI_SHIFT
TPOTDNELECTLIM      = 1.d-4    # Limit for amount of electron changed for updating VRATE.
TPOTGCENERGY        = .TRUE.   # Calculate grand canonical energy
TPOTGCIONIC         = .TRUE.   # Calculate grand canonical energy only at the end of ionic iteration

Thanks,
Dongmin

**Comment by zoowe** [comment]
Hi Dongmin,

Normally, if the relaxation require 20 or more steps, the system should reach the target potential. However, if starting NELECT is far from the value that give correct potential, it may need a lot more iterations to reach target potential (increase TPOTELECTSTEP would help reaching target potential faster but it may make calculation hard to converge)

If it stops before target potential reaches, I do exactly what you did, (IBRION = -1 with large TPOTELECTSTEP  to obtain correct NELECT and then continue relaxation with new NELECT). You can also do this step before relaxation to have good starting NELECT, which will prevent the issue.

In the past, I attempted to make sure target potential is one of the criteria for convergence. However, it requires a lot of change to the VASP code and code structure. That is why it is not implemented.

**Comment by pdmmicc** [comment]
Dear Duy, 

Thank you for your prompt reply. 

I have a few follow-up + additional questions on TPOT. 

1. As you mentioned, the system does indeed reach _near_ the target potential for 20+ (sometimes even less) ionic steps for a geometry relaxation run, and I've always started with an NELECT close to the expected value for the target potential (within <0.1~0.2e). However, it does not always fall within TPOTVDIFF towards the end of the run. For example, if I set TPOTVTARGET = 4.44 and TPOTVDIFF = 0.001, I sometimes get "CURRENT POTENTIAL" values of 4.42~4.46. Is this behavior expected, or am I missing something?

What I'm assuming from looking at the TPOT source code is that TPOTVDIFF is used as a criteria for changing NELECT for the next step, so when we reach the force criteria for the VASP run to stop for a relaxation run, the potential might not be within TPOTVDIFF. I understand that using the target potential as the stop criteria is not implemented here. So what would be the best protocol to follow after force convergence is reached, and potential is _close_ to the target potential? 

As my own solution, I ran static calculations on the optimized geometry (IBRION=-1, and NSW=20~100) and simply selected configurations and energies where the target potential was reach within TPOTVDIFF. I think there could be some better way maybe (like switching from TPOTMETHOD=2 to 1 on the optimized geometry? I don't know). 

2. (Suggestion rather than a question) When running static calculations on the optimized geometry, something I've encountered is that the VRATE (with TPOTDYNVRATE=True) fluctuates and has relatively large magnitudes (10~80) with sometimes even a positive sign for small (<0.001) NELECT changes near the target potential. I think maybe some damping factor for small NELECT changes when potential is near the target potential could help reduce some fluctuations and better reach within TPOTVDIFF.


3. With regard to doing NEB calculations with TPOT, I could do one of the following schemes:

Scheme A: Constant charge NEB -> (Single-point calc) Charging each image near target potential -> NEB with target potential 

Scheme B: (Single-point calc) Charging each image (initial configurations) near target potential -> NEB with target potential 

For a reaction like CO2* -> COOH*, the potential difference between the IS and FS is as large as 1V (for constant charge NEB), so Scheme A might give different TS or intermediate configurations (i.e. mapping a different MEP than a constant-potential NEB). But I'm worried that using Scheme B may be more costly as initial geometry optimization steps usually takes the longest computation time. Would the additional computation cost for implementing TPOT be significant when starting with initial input configurations for standard NEB calculations? 

4. (Following from Q3) From your experience, what is usually the added cost (e.g. 10% more ionic steps) of using TPOT, not just for NEB but routine geometry relaxation calculations (given that you start with a reasonable initial NELECT)? 


Would really appreciate your opinions. 

Best regards,
Dongmin

**Comment by zoowe** [comment]
Hi Dongmin,

1. It will always be the case. Since the method you use did not optimize number of electron during SCF step, we will always see fluctuation of potential. This is the trade off for gaining speed. I observe that the fluctuation is much smaller when using TPOTTRUEVACLEVEL = .FALSE. 
(I have tried a few simple approach to get calculation stop only when target potential reach, include what you suggest. The problem is that we do not want to make too many change  VASP code which will make it hard for new version).

3. I would do NEB with TPOT. Starting NELECT for each image can be interpolated between IS and FS. You can set NELECT for each image with in TPOTCAR in each folder (just has only starting NELECT for each image). After about 10-20 iterations, all image will reach target potential. We do NEB calculation this way.
4. If the change of NELECT between ionic step is not substantial, we should not expect a lot of additional cost. Depending on system, but I would say about 5-10% more if  TPOTTRUEVACLEVEL = .TRUE. but minimal with TPOTTRUEVACLEVEL = .FALSE..

**Comment by pdmmicc** [comment]
Dear Duy, 

Your comments helped a lot. 

And again, thanks for the prompt reply!
