### ISSUE TITLE
vaspsol plane average of ERRFC

### ISSUE THREAD

**Issue by bujianbusan123-alt** [zoowe/tpot#5]
Hi， very  nice work, could you please tell me how to output plane average of ERRFC (shape function) using VASPsol ?

**Comment by zoowe** [comment]
Hi, 
You can use LWRITEEPS = .TRUE. and NWRITE_ITERS = N. N determines how many electronic iterations that the code skips before writing. This is Epsilon, you can convert it back to shape function.

D.

PS. I am closing this as it is not an issue.
Please consider to join the discussion group: https://groups.google.com/g/tpot_simulation
