### ISSUE TITLE
How to choose the parameter `SIGMA_SH`

### ISSUE THREAD

**Issue by xke123502** [zoowe/tpot#6]
Dear developer, 
Thank you for your sharing. I'm working on how to use the SOLHYBRID model. I got how ALPHA_SH is seleted from your paper (shape function, bound charge density and ion charge density) , but how about SIGMA_SH?

**Comment by zoowe** [comment]
As of now, I do not have any rule for choosing this value. My test showing that SIGMA_SH = 1 Angstrom (convert to direct coordinate) is a stable parameter.

**Comment by xke123502** [comment]
Thank you.
