### ISSUE TITLE
Questions on TPOTTRUEVACLEVEL  

### ISSUE THREAD

**Issue by bujianbusan123-alt** [zoowe/tpot#7]
Hi Mr Zoowe:
      On "TPOTTRUEVACLEVEL  = .TRUE.   # Use true vacuum level or FERMI_SHIFT",
why do you set two choices ? how to determined True of False according to specific system ?

**Comment by zoowe** [comment]
The electrostatic potential level in the bulk electrolyte region reported by VASPSol is not consistent with that obtained from LOCPOT. It has been mentioned elsewhere https://github.com/henniggroup/VASPsol/issues/51
This option allows user to choose one of these values for for electrostatic potential in the bulk electrolyte region.
