### ISSUE TITLE
TPOT is suitable for implicit model without any solvent ?

### ISSUE THREAD

**Issue by bujianbusan123-alt** [zoowe/tpot#8]
Hi teacher: 

     TPOT is suitable for implicit model without any solvent when applied constant potential ?

**Comment by zoowe** [comment]
Yes. It will work without explicit solvent. The following is the standard input


LSOL       = .TRUE.
EB_k       = 78.4
LAMBDA_D_K = 3.04
CORE_C     =   #Number of core electron for each type
TAU        = 0  

#TPOT
LTPOT            = .TRUE.
TPOTMETHOD       = 2
TPOTTRUEVACLEVEL = .TRUE.
TPOTVTARGET      = 4.44  # 0 V vs SHE
TPOTVDIFF        = 0.01
TPOTELECTSTEP    = 0.5
TPOTDYNVRATE     = .TRUE.
TPOTVRATE        = -1
TPOTVRATELIM     = 0.05
TPOTGCENERGY     = .TRUE.
TPOTGCIONIC      = .TRUE.
NELECT           = Starting number of electron
