### ISSUE TITLE
Fail to compile with VASP.6.3.2

### ISSUE THREAD

**Issue by RedStar-Iron** [zoowe/tpot#9]
Dear Duy,

When I compiled the vasp.6.3.2 with tpot, it gives me the error information below,

```
targetpot.F(191): error #6404: This name does not have a type, and must have an explicit type.   [VACPOT]
      FERMI_SHIFT  = VACPOT
---------------------^
compilation aborted for targetpot.f90 (code 1)
make[2]: *** [makefile:166: targetpot.o] Error 1
```

Could you give me some advice to fix this problem?

Thanks,
Guangsheng

**Comment by zoowe** [comment]
We have resolved this issue. The solution is
- Follow the 4 steps for installation https://github.com/zoowe/tpot
- Apply the batch [VASPsol_VASP630](https://github.com/henniggroup/VASPsol/files/8495230/VASPsol_VASP630.zip)
